name: env_learnmesh
channels:
  - pytorch
  - conda-forge
  - dglteam/label/th24_cu121
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=2.1.0
  - archspec=0.2.3
  - asttokens=2.0.5
  - blas=1.0
  - boltons=23.0.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - cffi=1.17.1
  - cftime=1.6.2
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - conda=24.7.1
  - conda-libmamba-solver=24.9.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - contourpy=1.2.0
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - cuda-version=12.4
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - dgl=2.4.0.th24.cu121
  - dill=0.3.8
  - distro=1.9.0
  - double-conversion=3.1.5
  - eigen=3.4.0
  - einops=0.8.0
  - executing=0.8.3
  - expat=2.6.3
  - ffmpeg=4.2.2
  - filelock=3.13.1
  - fmt=9.1.0
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozendict=2.4.2
  - geos=3.10.6
  - gl2ps=1.4.2
  - glew=2.2.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - grpcio=1.62.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.11.0
  - hdf4=4.2.13
  - hdf5=1.12.1
  - icu=73.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jsoncpp=1.9.4
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libarchive=3.6.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.1.3
  - libcups=2.4.2
  - libcurand=10.3.5.147
  - libcurl=8.9.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libglu=9.0.0
  - libgomp=11.2.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnetcdf=4.8.1
  - libnghttp2=1.57.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libvpx=1.7.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libzip=1.8.0
  - llvm-openmp=14.0.6
  - loguru=0.7.2
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - menuinst=2.1.2
  - meshio=5.3.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpmath=1.3.0
  - mysql=5.7.24
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - netcdf4=1.6.2
  - nettle=3.7.3
  - networkx=3.3
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=10.4.0
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - proj=6.2.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=4.25.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.1.2
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.7
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qt=5.15.9
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - re2=2022.04.01
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - rich=13.7.1
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - setuptools=75.1.0
  - shapely=2.0.6
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.13.2
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - torchaudio=2.4.1
  - torchtriton=3.0.0
  - torchvision=0.19.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - truststore=0.8.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - utfcpp=3.2.1
  - vtk=9.0.3
  - wcwidth=0.2.5
  - werkzeug=3.0.3
  - wheel=0.44.0
  - x264=1!157.20191217
  - xz=5.4.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - fsspec==2024.9.0
      - jaxtyping==0.2.19
      - linear-operator==0.5.2
      - multipledispatch==1.0.0
      - opt-einsum==3.3.0
      - pip==25.1.1
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - typeguard==2.13.3
